services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    networks:
      - mine
    ports:
      - "443:443"
      - "80:80"
    environment:
      - NGINX_HOST=monerokoszudikas.duckdns.org
      - NGINX_PORT=80
    volumes:
      - nginx-data:/etc/nginx
    restart: unless-stopped

volumes:
  nginx-data:

networks:
  mine:
    external: true
    name: mine