services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 5`Q7l*0(=7z?
    networks:
      - mine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Script/PostgresDb/:/Script/PostgresDb
    restart: unless-stopped

volumes:
  postgres-data:
    
networks:
  mine:
    external: true
    name: mine
